name       : pangomm
version    : 2.40.0
release    : 6
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/pangomm/2.40/pangomm-2.40.0.tar.xz : 7dd0afa9dcce57cdb0aad77da9ea46823ee8515d5f3ffd895b9ede7365c3d70d
license    :
    - LGPL-2.0
summary    : C++ binding to pango
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangocairo)
patterns   :
    - devel :
        - /usr/lib64/pangomm-1.4
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
description: |
    C++ binding to pango
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
