name       : pangomm
version    : 2.46.3
release    : 19
source     :
    - https://download.gnome.org/sources/pangomm/2.46/pangomm-2.46.3.tar.xz : 410fe04d471a608f3f0273d3a17d840241d911ed0ff2c758a9859c66c6f24379
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : C++ bindings to pango
description: |
    C++ bindings to pango
optimize   : speed
builddeps  :
    - pkgconfig(cairomm-1.0)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(pangocairo)
patterns   :
    - devel : /usr/lib64/pangomm-1.4
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
