name       : pangomm
version    : 2.46.1
release    : 18
source     :
    - https://download.gnome.org/sources/pangomm/2.46/pangomm-2.46.1.tar.xz : c885013fe61a4c5117fda395770d507563411c63e49f4a3aced4c9efe34d9975
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : C++ binding to pango
description: |
    C++ binding to pango
optimize   : speed
builddeps  :
    - pkgconfig(cairomm-1.0)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(pangocairo)
patterns   :
    - devel : /usr/lib64/pangomm-1.4
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
