name        : pangomm
version     : 2.36.0
release     : 4
source      :
    - http://ftp.acc.umu.se/pub/gnome/sources/pangomm/2.36/pangomm-2.36.0.tar.xz : a8d96952c708d7726bed260d693cece554f8f00e48b97cccfbf4f5690b6821f0
homepage    : http://www.gnome.org
license     :
    - LGPL-2.0
summary     : C++ binding to pango
builddeps   :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangocairo)
patterns    :
    - devel:
        - /usr/lib64/pangomm-1.4
    - docs:
        - /usr/share/devhelp
        - /usr/share/doc
description : |
    C++ binding to pango
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
