name       : pangomm
version    : 2.40.1
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/pangomm/2.40/pangomm-2.40.1.tar.xz : 9762ee2a2d5781be6797448d4dd2383ce14907159b30bc12bf6b08e7227be3af
license    : LGPL-2.0
component  : desktop.library
summary    : C++ binding to pango
description: |
    C++ binding to pango
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangocairo)
patterns   :
    - devel :
        - /usr/lib64/pangomm-1.4
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
optimize   : speed
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
