name        : pangomm
version     : 2.38.1
release     : 5
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/pangomm/2.38/pangomm-2.38.1.tar.xz : effb18505b36d81fc32989a39ead8b7858940d0533107336a30bc3eef096bc8b
license     :
    - LGPL-2.0
summary     : C++ binding to pango
builddeps   :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(cairomm-1.0)
    - pkgconfig(pangocairo)
patterns    :
    - devel:
        - /usr/lib64/pangomm-1.4
    - docs:
        - /usr/share/devhelp
        - /usr/share/doc
description : |
    C++ binding to pango
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
